stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/data.csv
    params:
      - preprocess.input
      - preprocess.output
      - preprocess.scaler_path
    outs:
      - data/processed/data.csv
      - models/scaler.pkl

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/data.csv
    params:
      - train.data
      - train.model
      - train.random_state
      - train.n_estimators
      - train.max_depth
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed/data.csv
      - models/model.pkl
    params:
      - evaluate.data
      - evaluate.model
    metrics:
      - metrics.json:
          cache: false