preprocess:
  input: data/raw/data.csv
  output: data/processed/data.csv
  scaler_path: models/scaler.pkl

train:
  data: data/processed/data.csv
  model: models/model.pkl
  random_state: 42
  n_estimators: 200
  max_depth: 15
  min_samples_split: 5
  min_samples_leaf: 2
  max_features: 'sqrt'
  class_weight: 'balanced'

evaluate:
  data: data/processed/data.csv
  model: models/model.pkl

stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/data.csv
    params:
      - preprocess.input
      - preprocess.output
      - preprocess.scaler_path
    outs:
      - data/processed/data.csv
      - models/scaler.pkl
